<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.2.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="RestSharp" Version="114.0.0"/>
        <PackageReference Include="RestSharp.Serializers.NewtonsoftJson" Version="114.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GameProfile.Utils\GameProfile.Utils.csproj"/>
    </ItemGroup>

</Project>
